// Run: TZ=Asia/Riyadh node --test tests/regression.cjs
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
function block(start,end){return html.slice(html.indexOf(start),html.indexOf(end,html.indexOf(start)));}
function context(extra={}){const c={console,Set,Date,JSON,String,encodeURIComponent,session:{user:{id:'me'}},SB_URL:'https://example.invalid',apiHeaders:()=>({}),myName:()=> 'سامي',daysUntil:()=>1,render:()=>{},toast:()=>{},notify:async()=>{},loadAll:async()=>{},toGregShort:s=>s,...extra};vm.createContext(c);return c;}
test('all inline scripts parse',()=>{for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);});
test('auth event updates REST token',async()=>{const c=context({_loggedIn:true,sb:{auth:{onAuthStateChange:f=>c.cb=f}}});vm.runInContext(block('  sb.auth.onAuthStateChange','  try{'),c);await c.cb('TOKEN_REFRESHED',{access_token:'new'});assert.equal(c.session.access_token,'new');});
test('local day survives positive timezone and month/year boundaries',()=>{const c=context();vm.runInContext(block('function localISO','function esc'),c);for(const [day,delta,expected] of [['2026-10-08',1,'2026-10-09'],['2026-10-01',-1,'2026-09-30'],['2026-12-31',1,'2027-01-01']]){const d=new Date(day+'T00:00:00');d.setDate(d.getDate()+delta);assert.equal(c.localISO(d),expected);}});
test('names round-trip safely through HTML onclick attributes',()=>{const c=context();vm.runInContext(block('function jsArg','// ── توقيت الرياض'),c);const decode=s=>s.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');for(const name of ["O'Brien",'";globalThis.injected=true;//','علي & أحمد','\\x27']){assert.equal(vm.runInContext(decode(c.jsArg(name)),c),name);assert.equal(c.injected,undefined);}});
test('suggestion uses title input',async()=>{let sent;const c=context({document:{getElementById:id=>({value:{sugTitle:'فكرة',sugBody:'تفاصيل',sugCat:'general'}[id]})},D:{suggestions:[]},checkedFetch:async(u,o)=>{sent=JSON.parse(o.body);return {ok:true,json:async()=>[{id:'new',...sent}]};},renderSuggestions:()=>{}});vm.runInContext('globalThis.addSuggestion=async function(){'+block('  async addSuggestion(){','  async delSuggestion(').split('async addSuggestion(){')[1].replace(/\},\s*$/,'}') ,c);await c.addSuggestion();assert.equal(sent.title,'فكرة');assert.equal(c.D.suggestions.length,1);});
test('failed RSVP preserves previous status; successful upsert replaces it',async()=>{const c=context({D:{slots:[{id:'s',host_name:'فهد'}],rsvps:[{slot_id:'s',member_name:'سامي',status:'no'}]},checkedFetch:async()=>{throw Error('denied')}});vm.runInContext(block('const _rsvpSaving','const _swapResolving'),c);await c.setRsvp('s','yes');assert.equal(c.D.rsvps[0].status,'no');c.checkedFetch=async(u,o)=>{assert.match(u,/on_conflict=slot_id,member_name/);return {json:async()=>[{id:'r',...JSON.parse(o.body)}]};};await c.setRsvp('s','yes');assert.equal(c.D.rsvps[0].status,'yes');assert.equal(c.D.rsvps.length,1);});
test('booking conflict never changes host or sends success notifications',async()=>{let notified=0;const c=context({D:{settings:{allow_multi_booking:'true'},slots:[{id:'s',date:'2026-10-09',host_name:null}]},withLoading:async(b,f)=>f(),checkedFetch:async(u,o)=>{assert.match(u,/host_name=is.null/);return {json:async()=>[]};},notifyAll:async()=>notified++});vm.runInContext(block('async function bookSlot','async function cancelBookSlot'),c);await assert.rejects(()=>c.bookSlot('s'));assert.equal(c.D.slots[0].host_name,null);assert.equal(notified,0);});
test('swap RPC failure preserves both slots and pending request',async()=>{const c=context({D:{slots:[{id:'a',date:'2026-10-09',host_name:'فهد'},{id:'b',date:'2026-11-09',host_name:'سامي'}],swaps:[{id:'q',from_slot_id:'a',to_slot_id:'b',requester_name:'فهد'}]},checkedQuery:async()=>{throw Error('denied')},sb:{rpc:(name,args)=>{assert.equal(name,'resolve_swap_atomic');assert.equal(args.p_swap_id,'q');return Promise.resolve({});}}});vm.runInContext(block('const _swapResolving','async function adjustHijri'),c);await c.resolveSwap('q',true);assert.equal(c.D.slots[0].host_name,'فهد');assert.equal(c.D.slots[1].host_name,'سامي');assert.equal(c.D.swaps.length,1);});
test('HTTP failure rejects a write but read retains fallback',async()=>{const c=context({window:{fetch:async()=>({ok:false,status:403})}});vm.runInContext(block('async function checkedFetch','async function checkedQuery'),c);await assert.rejects(()=>c.checkedFetch('x',{method:'PATCH'}));assert.equal((await c.checkedFetch('x')).ok,false);});
test('calendar detail chips and pending count exclude the host',()=>{const start=html.indexOf('async function openCalSlotModal');const part=html.slice(start);const code=part.slice(part.indexOf('  const sRsvp'),part.indexOf('  const myRv'));const c=context({slot:{id:'s',host_name:'المضيف'},esc:s=>s,D:{team:[{name:'المضيف'},{name:'سامي'},{name:'فهد'}],rsvps:[{slot_id:'s',member_name:'المضيف',status:'yes'},{slot_id:'s',member_name:'سامي',status:'yes'}]}});vm.runInContext(code+';globalThis.result={chips,yes,no,pending:attendees.length-yes-no};',c);assert.equal(c.result.chips.includes('المضيف'),false);assert.equal(c.result.yes,1);assert.equal(c.result.pending,1);});
